# Generated by Django 5.2.1 on 2025-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusPiloto',
            fields=[
                ('id_bus_piloto', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bus_piloto',
                'managed': False,
            },
        ),
    ]
