# Generated by Django 5.2.1 on 2025-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id_operador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.CharField(blank=True, max_length=50, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'operador',
                'managed': False,
            },
        ),
    ]
