# Generated by Django 5.2.1 on 2025-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineaEstacion',
            fields=[
                ('id_linea_estacion', models.AutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField()),
                ('distancia_a_siguiente', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'linea_estacion',
                'managed': False,
            },
        ),
    ]
