# Generated by Django 5.2.1 on 2025-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parqueo',
            fields=[
                ('id_parqueo', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'parqueo',
                'managed': False,
            },
        ),
    ]
