# Generated by Django 5.2.1 on 2025-05-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id_piloto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('escolaridad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'piloto',
                'managed': False,
            },
        ),
    ]
